"""add paper_trades table

Revision ID: 055314771c35
Revises: 81777b4b3b49
Create Date: 2026-03-31 18:50:37.376500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055314771c35'
down_revision: Union[str, Sequence[str], None] = '81777b4b3b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signal_time', sa.DateTime(), nullable=False),
    sa.Column('candle_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('level_types_json', sa.Text(), nullable=True),
    sa.Column('breakeven_reached', sa.Boolean(), nullable=True),
    sa.Column('current_trail_sl', sa.Float(), nullable=True),
    sa.Column('bars_since_entry', sa.Integer(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl_r', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_trades_signal_time', 'paper_trades', ['signal_time'], unique=False)
    op.create_index('idx_paper_trades_status', 'paper_trades', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_paper_trades_status', table_name='paper_trades')
    op.drop_index('idx_paper_trades_signal_time', table_name='paper_trades')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
