"""Add individual level backtest tables

Revision ID: 44d9feded03e
Revises: 14161ac4dd08
Create Date: 2026-02-16 18:14:02.573984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d9feded03e'
down_revision: Union[str, Sequence[str], None] = '14161ac4dd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_level_backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_type', sa.String(length=50), nullable=False),
    sa.Column('level_source_timeframe', sa.String(length=10), nullable=False),
    sa.Column('trade_execution_timeframe', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('avg_trade_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ilb_created', 'individual_level_backtests', ['created_at'], unique=False)
    op.create_index('idx_ilb_level_type', 'individual_level_backtests', ['level_type'], unique=False)
    op.create_index('idx_ilb_source_tf', 'individual_level_backtests', ['level_source_timeframe'], unique=False)
    op.create_index('idx_ilb_status', 'individual_level_backtests', ['status'], unique=False)
    op.create_index('idx_ilb_strategy', 'individual_level_backtests', ['strategy_name'], unique=False)
    op.create_table('individual_level_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('candles_held', sa.Integer(), nullable=True),
    sa.Column('entry_volatility', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('distance_to_level', sa.Float(), nullable=True),
    sa.Column('zone_confluence', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['individual_level_backtests.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ilt_backtest', 'individual_level_trades', ['backtest_id'], unique=False)
    op.create_index('idx_ilt_direction', 'individual_level_trades', ['direction'], unique=False)
    op.create_index('idx_ilt_entry_time', 'individual_level_trades', ['entry_time'], unique=False)
    op.create_index('idx_ilt_exit_reason', 'individual_level_trades', ['exit_reason'], unique=False)
    op.create_index('idx_ilt_level', 'individual_level_trades', ['level_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ilt_level', table_name='individual_level_trades')
    op.drop_index('idx_ilt_exit_reason', table_name='individual_level_trades')
    op.drop_index('idx_ilt_entry_time', table_name='individual_level_trades')
    op.drop_index('idx_ilt_direction', table_name='individual_level_trades')
    op.drop_index('idx_ilt_backtest', table_name='individual_level_trades')
    op.drop_table('individual_level_trades')
    op.drop_index('idx_ilb_strategy', table_name='individual_level_backtests')
    op.drop_index('idx_ilb_status', table_name='individual_level_backtests')
    op.drop_index('idx_ilb_source_tf', table_name='individual_level_backtests')
    op.drop_index('idx_ilb_level_type', table_name='individual_level_backtests')
    op.drop_index('idx_ilb_created', table_name='individual_level_backtests')
    op.drop_table('individual_level_backtests')
    # ### end Alembic commands ###
