"""add level_price to individual_level_trades

Revision ID: bfc812709a55
Revises: 44d9feded03e
Create Date: 2026-02-17 10:27:30.285393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc812709a55'
down_revision: Union[str, Sequence[str], None] = '44d9feded03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_level_trades', sa.Column('level_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual_level_trades', 'level_price')
    # ### end Alembic commands ###
